### ISSUE TITLE
At least one cross reference to an appendix is broken

### ISSUE THREAD

**Issue by AllenDowney** [AllenDowney/ThinkPerl6#10]
For example, at the top of page 43, the reference

    Subsection~\ref{sol_cartalk}

Gets translated into the DocBook

    <xref linkend="sol_cartalk" />

Which is defined

    <sect2 id="sol_cartalk" remap="subsection">

But it is being rendered

     “???: Consecutive double letters ” on page 388"

Since other references to subsections are working, I conjecture that the problem is that the target of this reference is in an appendix.

@hackermatthew , you looked into this: does this info help?

**Comment by kristenORM** [comment]
I think I mostly have the xrefs sorted out. There are now only two that reference a section that doesn't exist; I've flagged these in the CE PDF for your attention later in review.

**Comment by LaurentRosenfeld** [comment]
OK, fine. We'll fixed that then.

**Comment by LaurentRosenfeld** [comment]
Hi Kristen,

it seems that I have no longer access to the Atlas repo (
https://atlas.oreilly.com/oreillymedia/think-perl6).

Has it been moved?  Or anything alse that I am not ware of?

Cheers,
Laurent.


2017-03-20 17:52 GMT+01:00 Kristen Brown <notifications@github.com>:

**Comment by kristenORM** [comment]
It has not moved, I was using it just this morning! Looks like we may have an Atlas/Amazon AWS hiccup. I'll find out what's going on.

**Comment by kristenORM** [comment]
Ah, we changed the name:
https://atlas.oreilly.com/oreillymedia/think-perl-6

Note the hyphen between perl and 6, which was not there in the old repo.

**Comment by LaurentRosenfeld** [comment]
OK, fine. We'll fixed that then.

**Comment by LaurentRosenfeld** [comment]
This is now fixed. Closing the issue.
