### ISSUE TITLE
Page numbering between front matter and main body of the text

### ISSUE THREAD

**Issue by LaurentRosenfeld** [AllenDowney/ThinkPerl6#11]
Hm, not sure that this is an issue at all, this may be perfectly legitimate, so I am just asking just to make sure it does not go unnoticed.

In the PDF generated from LaTeX, the front matter has pages numbered in Roman numerals, say I to XIX, or something similar. Then, the first chapter has pages in Arabic numerals, starting at 1 and going to 390, or whatever.

In the PDF generated from DocBook, the preface ends on page XX, and the main matter (chapter 1) starts with page number 23 (with two blank numeration pages in between). So in effect, we have the following page succession: XX, (none), (none), 23.

This is perfectly consistent and I have absolutely no problem with that, I just wonder if this is the usual policy of O'Reilly. I have just looked at several books, including two relatively recent ones from O'Reilly (such as Programming Perl (4th E)), it seems that the normal policy is to restart numbering at 1 when getting to the book main matter (that's also what Lamport and Knuth do in their LaTeX and TeX books, but, with all due respect to them, I would not mind very much departing from them on such trivia).

Frankly, I personally don't care, so I am just asking Matt if O'Reilly has a definite policy on such page numbering, or if this an artifact due to the conversion. If not, anyone please close this issue.

**Comment by kristenORM** [comment]
This is done now (will be visible in the CE PDF), so I think we can close this issue.

**Comment by LaurentRosenfeld** [comment]
OK, if this is now OK, fine with me to close the issue.
