### ISSUE TITLE
[Early Release HTML rendering] Color change

### ISSUE THREAD

**Issue by LaurentRosenfeld** [AllenDowney/ThinkPerl6#13]
Chapter 1, The Way of the program (https://library.oreilly.com/book/0636920065883/think-perl-6/12.xhtml?ref=toc#a0000000126). The color changes suddenly in the middle of the page (black to red), and stays red for at least several other HTML pages.

**Comment by kristenORM** [comment]
I don't see this problem in the PDF; can we close this because it will be corrected when we replace the Early Release with the final release at the end of production?

**Comment by LaurentRosenfeld** [comment]
Hi Kristen,
we did not have this problem in the PDF, but only in the HTML posted as early release.  I guess you can close it if you're sure this will go away later in the production.
