### ISSUE TITLE
[Early Release HTML rendering] Math fraction  improperky rendered

### ISSUE THREAD

**Issue by LaurentRosenfeld** [AllenDowney/ThinkPerl6#14]
In section "Values and types" of Chapter 1 (https://library.oreilly.com/book/0636920065883/think-perl-6/16.xhtml?ref=toc#a0000000126), the fraction 173/10 is improperly rendered.

**Comment by kristenORM** [comment]
I will leave a sticky note by these items in the CE PDF so you can make sure they look correct in that format.

**Comment by LaurentRosenfeld** [comment]
The rendering is OK in the PDF, it's just in the HTML where it is faulty. A sticky note is fine with me.
