### ISSUE TITLE
Section 4.15 sub MAIN verbiage

### ISSUE THREAD

**Issue by nooninm** [AllenDowney/ThinkPerl6#15]
Per book section 4.15 the MAIN subroutine executes first.  The opposite is true.  It executes last.  Test script on Windows 7 is below, with results.

sub execute_after_main(Str $string) {
    say "\tDid this $string print out after MAIN was done?";
}
execute_after_main("1");
	
sub MAIN() {
    say "\tThis is main so this should print first";
}
execute_after_main("2");

#Result:
#       Did this 1 print out after MAIN was done?
#       Did this 2 print out after MAIN was done?
#       This is main so this should print first

**Comment by LaurentRosenfeld** [comment]
Yes, you're right, saying that "a program will usually start its execution" with the MAIN subroutine is not really correct. One of the reasons for this mistake is in the official documentation which is, at best, misleading. In general, I would suggest that it is probably not a good idea to have executable code statements outside of any subroutine when there is a MAIN sub: IMHO, when there is a MAIN sub, all executable code statements should usually be in the MAIN sub or in subroutines called (directly or indirectly) by MAIN.

Please note that this repository is no longer maintained and out-of-date. If you want to see the up-to-date version (with all the latest corrections and typo fixes), please go to this Github repository: https://github.com/LaurentRosenfeld/thinkperl6/.
