### ISSUE TITLE
Footers on even pages are broken

### ISSUE THREAD

**Issue by AllenDowney** [AllenDowney/ThinkPerl6#4]
Next, I don't know if this has to do with the format conversion or something else, but the footers on even pages are messy (at least, chapter number is totally wrong, but there may be more to it, I don't even understand the logic of the problem).

**Comment by kristenORM** [comment]
This is corrected in the CE PDF.

**Comment by AllenDowney** [comment]
Confirmed.  For future reference, what was the problem?  Is this something
I could have fixed in the DocBook I generate?

**Comment by kristenORM** [comment]
@hackermatthew do you know? Was this a matter of breaking the document into separate chapter files?

**Comment by LaurentRosenfeld** [comment]
OK, if this is now solved, I guess we can close the issue.

**Comment by hackermatthew** [comment]
@AllenDowney I checked the history, and the footnote numbering issue got resolved when we switched this project from the default version of the PDF build software installed on Atlas to the one we typically use once a book hits production. If this happens on PDF builds of a future book while you're writing, we can try switching the version.

**Comment by AllenDowney** [comment]
Got it.  Thank you!
